import type { NextPage } from 'next';
import Head from 'next/head';
import HelloWorld from '@components/HelloWorld';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HelloWorld />
    </div>
  );
};

export default Home;
